# Generated by Django 4.0.4 on 2022-05-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='latitude',
            new_name='latitude_end',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='longitude',
            new_name='latitude_start',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='longitude_end',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinates',
            name='longitude_start',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
