# Generated by Django 4.0.4 on 2022-05-29 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_latitude_coordinates_latitude_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='API.dog'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.trainer'),
        ),
    ]
