# Generated by Django 4.0.4 on 2022-05-29 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_dog_behavior_dog_prohibitions_dog_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerreview',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
