# Generated by Django 4.0.4 on 2022-05-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_trainerreview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(upload_to='media/dog_photos'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='photo',
            field=models.ImageField(upload_to='media/profile_photos'),
        ),
    ]
